CI test for minimal python & deps versions support (#827)
Hi,

could you please review proposal to have a CI test against checking the
minimal support python and deps version can pass the test suite. It
fixes #826.

The job is expected to fail the first time it runs, because attrs
minimal version of 20.1.0 fails to bootstrap the tests, which is also
proving the point of this patch.

It will subsequently be corrected to the next available version which
will pass the test.

Thanks

---------

Co-authored-by: ikappaki <ikappaki@users.noreply.github.com>

diff --git a/.github/workflows/run-tests.yml b/.github/workflows/run-tests.yml
--- a/.github/workflows/run-tests.yml
+++ b/.github/workflows/run-tests.yml
@@ -77,6 +77,61 @@ jobs:
           name: code-coverage
           path: coverage/.coverage.py*
 
+  min-deps-test:
+    # Attempt to run the TOX-ENV tests for the given OS and python
+    # VERSION with the minimal possible Basilisp dependencies
+    # versions.
+    #
+    # For dependencies to be elligible for minimum version testing,
+    # they should be declared in `pyproject.toml` as such in the
+    # following format
+    #
+    # <dependency-name> = "^..."
+    # <dependency-name> = ">=..."
+    # <dependency-name> = { version = "^..." ...
+    # <dependency-name> = { version = ">=..." ...
+    runs-on: ${{matrix.os}}
+    strategy:
+      matrix:
+        os: [ubuntu-latest]
+        version: ['3.8']
+        tox-env: ['py38']
+    steps:
+      - uses: actions/checkout@v3
+      - uses: actions/setup-python@v4
+        with:
+          python-version: ${{ matrix.version }}
+      - name: Cache dependencies
+        id: cache-deps
+        uses: actions/cache@v3
+        with:
+          path: |
+            .tox
+            ~/.cache/pip
+            ~/.cache/pypoetry
+            ~/.local/share/pypoetry
+          key: mdt-${{ runner.os }}-python-${{ matrix.version }}-poetry-${{ hashFiles('pyproject.toml', 'tox.ini') }}
+      - name: Install Poetry
+        if: steps.cache-deps.outputs.cache-hit != 'true'
+        run: curl -sSL https://install.python-poetry.org | python3 -
+      - name: Install Tox
+        run: |
+          pip install -U pip
+          pip install tox
+      - name: Run minimum deps test
+        env:
+          TOX_PARALLEL_NO_SPINNER: 1
+          TOX_SHOW_OUTPUT: "True"
+          TOXENV: ${{ matrix.tox-env }}
+        run: |
+          poetry lock
+          DEPENDENCY_REGEX="$(poetry show -T --without=dev | awk '{print $1}' | paste -s -d '|' -)"
+          [[ -z "$DEPENDENCY_REGEX" ]] && { echo "Error: can't source dependencies" ; exit 1; }
+          echo ::deps $DEPENDENCY_REGEX
+          sed -i -E 's/('$DEPENDENCY_REGEX')( = )(|\{ version = )"(\^|>=)([0-9])/\1\2\3"==\5/' pyproject.toml
+          git diff
+          tox run-parallel -p 2
+
   report-coverage:
     runs-on: ubuntu-latest
     needs: run-tests
